export enum StoreActionTypes {
    START_LOADING = 'START_LOADING',
    ALL_DATA_LOADED = 'ALL_DATA_LOADED',
    FIRST_PAGE_LOADED = 'FIRST_PAGE_LOADED',
    SET_PAGE_TO_LOAD = 'SET_PAGE_TO_LOAD',
    ADD_VOLUME_TO_CART = 'ADD_VOLUME_TO_CART'
}
